### ISSUE TITLE
No CUDA GPUs are available

### ISSUE THREAD

**Issue by nightfury1103** [khanld/ASR-Wav2vec-Finetune#3]
Hi, I try to train your model with my dataset. But I have a trouble

> Traceback (most recent call last):
>   File "train.py", line 196, in <module>
>     join = True
>   File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 240, in spawn
>     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
>   File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
>     while not context.join():
>   File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
>     raise ProcessRaisedException(msg, error_index, failed_process.pid)
> torch.multiprocessing.spawn.ProcessRaisedException: 
> 
> -- Process 0 terminated with the following error:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
>     fn(i, *args)
>   File "/content/ASR-Wav2vec-Finetune/train.py", line 129, in main
>     model = DDP(model.to(rank), device_ids=[rank], find_unused_parameters=True)
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 927, in to
>     return self._apply(convert)
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 579, in _apply
>     module._apply(fn)
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 579, in _apply
>     module._apply(fn)
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 579, in _apply
>     module._apply(fn)
>   [Previous line repeated 2 more times]
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 602, in _apply
>     param_applied = fn(param)
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 925, in convert
>     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
>   File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 217, in _lazy_init
>     torch._C._cuda_init()
> RuntimeError: No CUDA GPUs are available`

I train it with google colab and I turn on the GPU. But it doesn't work. :(

**Comment by khanld** [comment]
Try setting the device_ids='0' in the config.toml file so Torch can recognize the current GPU device

**Comment by nightfury1103** [comment]
Thank you so much!
